---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: prometheus

resources:
  - prometheus-cm.yml
  - account.yml
  - deployment.yml
  - rbac.yml
  - service.yml

# configMapGenerator:
#   - name: prometheus
#     files:
#       - prometheus-cm.yml

