apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cm.yml
- account.yml
- deployment.yml
- rbac.yml
- service.yml
- secret.yml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/created-by: kustomizer
    app.kubernetes.io/name: prometheus
