---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  labels:
    app.kubernetes.io/name: prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090
