---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beyla
  labels:
    app.kubernetes.io/name: beyla
rules:
  - apiGroups:
    - "apps"
    resources:
    - "replicasets"
    verbs:
    - "list"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "pods"
    - "services"
    - "nodes"
    verbs:
    - "list"
    - "watch"
    - "get"
