apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
data:
  mimir.yaml: |
    target: all,overrides-exporter

    activity_tracker:
      filepath: /data/metrics-activity.log

    multitenancy_enabled: false

    blocks_storage:
      bucket_store:
        sync_dir: /tsdb-sync/
        index_cache:
          backend: inmemory
          inmemory:
            max_size_bytes: 52428800
      storage_prefix: blocks
      tsdb:
        bigger_out_of_order_blocks_for_old_samples: true
        block_postings_for_matchers_cache_max_bytes: 26214400
        dir: /tsdb/
        flush_blocks_on_shutdown: true
        head_chunks_write_queue_size: 0
        head_postings_for_matchers_cache_max_bytes: 26214400
        memory_snapshot_on_shutdown: true
        series_hash_cache_max_size_bytes: 0
        timely_head_compaction_enabled: true
        wal_compression_enabled: true

    common:
      storage:
        backend: filesystem
        filesystem:
          dir: /data

    compactor:
      cleanup_interval: 1h
      data_dir: /compactor/
      deletion_delay: 1h

    distributor:
      remote_timeout: 5s

    ingester:
      ring:
        replication_factor: 1

    limits:
      cardinality_analysis_enabled: true
      compactor_blocks_retention_period: 15d
      enabled_promql_experimental_functions: all
      enabled_promql_extended_range_selectors: all
      out_of_order_time_window: 15m

    ruler_storage:
      backend: local
      local:
        directory: /rules

    ruler:
      rule_path: /ruler

    store_gateway:
      sharding_ring:
        replication_factor: 1
