apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
data:
  mimir.yaml: |
    target: all,overrides-exporter

    activity_tracker:
      filepath: /data/metrics-activity.log

    multitenancy_enabled: false
    no_auth_tenant: anonymous

    blocks_storage:
      bucket_store:
        sync_dir: /tsdb-sync/
        ignore_blocks_within: 0s
      storage_prefix: blocks
      tsdb:
        dir: /tsdb/
        wal_compression_enabled: true

    common:
      storage:
        backend: filesystem
        filesystem:
          dir: /data

    compactor:
      cleanup_interval: 1h
      data_dir: /compactor/
      deletion_delay: 1h

    distributor:
      remote_timeout: 5s

    ingester:
      ring:
        replication_factor: 1
      push_circuit_breaker:
        request_timeout: 10s

    limits:
      enabled_promql_experimental_functions: all

    ruler_storage:
      backend: local
      local:
        directory: /rules

    ruler:
      rule_path: /ruler

    store_gateway:
      sharding_ring:
        replication_factor: 1
