apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- account.yml
- cm.yml
- service.yml
- statefulset.yml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/created-by: kustomizer
    app.kubernetes.io/name: mimir
