apiVersion: v1
kind: Service
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9095
    targetPort: 9095
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: mimir
