apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
  annotations:
    prometheus.io/port: http
    prometheus.io/scrape: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
  serviceName: mimir
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: http
    spec:
      serviceAccountName: mimir
      automountServiceAccountToken: false
      containers:
      - args:
        # - '-config.file=/conf/mimir.yaml'
        - '-common.storage.backend=filesystem'
        - '-common.storage.filesystem.dir=/data'
        - '-ruler-storage.backend=local'
        - '-ruler-storage.local.directory=/rules'
        - '-blocks-storage.tsdb.wal-compression-enabled=true'
        - '-blocks-storage.tsdb.dir=/data/tsdb/'
        - '-blocks-storage.storage-prefix.sync_dir=/data/tsdb-sync/'
        - '-blocks-storage.tsdb.retention-period=15d'
        - '-activity-tracker.filepath=/data/metrics-activity.log'
        - '-store-gateway.sharding-ring.replication-factor=1'
        - '-querier.cardinality-analysis-enabled=true'
        image: grafana/mimir:2.13.0
        imagePullPolicy: IfNotPresent
        name: mimir
        ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 100m
            memory: "1Gi"
          requests:
            cpu: 50m
            memory: "512Mi"
        volumeMounts:
        - mountPath: /conf
          name: conf
        - name: data
          mountPath: /data
        - name: rules
          mountPath: /rules
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
      volumes:
        - name: data
          emptyDir:
            sizeLimit: "10Gi"
        - name: rules
          emptyDir:
            sizeLimit: "1Gi"
        - configMap:
            name: mimir
          name: conf
