apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
  annotations:
    prometheus.io/port: http
    prometheus.io/scrape: "true"
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
  serviceName: mimir
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: http
    spec:
      serviceAccountName: mimir
      automountServiceAccountToken: false
      containers:
      - args:
        - '-auth.multitenancy-enabled=false'
        - '-auth.no-auth-tenant=anonymous'
        - '-config.file=/conf/mimir.yaml'
        - '-compactor.blocks-retention-period=15d'
        - '-distributor.ha-tracker.enable-for-all-users=true'
        - '-querier.cardinality-analysis-enabled=true'
        - '-blocks-storage.storage-prefix=blocks'
        - '-ingester.out-of-order-time-window=15m'
        - '-log.format=json'
        - '-log.level=warn'
        image: grafana/mimir:2.17.0
        imagePullPolicy: IfNotPresent
        name: mimir
        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              divisor: '1'
              resource: limits.cpu
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              divisor: '1'
              resource: limits.memory
        ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: conf
          mountPath: /conf
        - name: data
          mountPath: /data
        - name: rules
          mountPath: /rules
        - name: ruler
          mountPath: /ruler
        - name: rules
          mountPath: /rules/anonymous
          subPath: anonymous
        - name: tsdb
          mountPath: /tsdb
        - name: tsdb-sync
          mountPath: /tsdb-sync
        - name: compactor
          mountPath: /compactor
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
      volumes:
        - name: data
          emptyDir:
            sizeLimit: "2Gi"
        - name: rules
          emptyDir:
            sizeLimit: "1Gi"
        - name: ruler
          emptyDir:
            sizeLimit: "1Gi"
        - name: tsdb
          emptyDir:
            sizeLimit: "5Gi"
        - name: tsdb-sync
          emptyDir:
            sizeLimit: "1Gi"
        - name: compactor
          emptyDir:
            sizeLimit: "1Gi"
        - name: conf
          configMap:
            name: mimir
          
