apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  labels:
    app.kubernetes.io/name: loki
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      log_level: warn

    common:
      path_prefix: /data
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      replication_factor: 1
      storage:
        filesystem:
          chunks_directory: /data/chunks
          rules_directory: /data/rules

    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    pattern_ingester:
      enabled: true

    limits_config:
      discover_log_levels: true
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      allow_structured_metadata: true
      volume_enabled: true

    schema_config:
      configs:
        - from: "2020-05-15"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            period: 24h
            prefix: index_

    storage_config:
      tsdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/tsdb-cache
      filesystem:
        directory: /data/loki/chunks

    ruler:
      enable_api: true

    compactor:
      working_directory: /data/compactor
      retention_enabled: true
      delete_request_store: filesystem
