---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
      annotations:
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: promtail
      automountServiceAccountToken: true
      containers:
        - name: promtail
          image: docker.io/grafana/promtail:main
          imagePullPolicy: IfNotPresent
          args:
          - -config.file=/etc/promtail/kubernetes-config.yaml
          env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          ports:
            - name: http-metrics
              containerPort: 3101
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          volumeMounts:
          - name: config-volume
            mountPath: /etc/promtail
          - name: run
            mountPath: /run/promtail
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: mntpods
            mountPath: /mnt/kubelet/pods
            readOnly: true
          - name: mntlibdockercontainers
            mountPath: /mnt/docker/containers
            readOnly: true
          - name: tmp
            mountPath: /tmp
            subPath: tmp
            readOnly: false
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            runAsUser: 0
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config-volume
          configMap:
            name: promtail
        - name: run
          hostPath:
            path: /run/promtail
        - name: varlog
          hostPath:
            path: /var/log
        - name: mntlibdockercontainers
          hostPath:
            path: /mnt/docker/containers
        - name: mntpods
          hostPath:
            path: /mnt/kubelet/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
