---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: promtail

resources:
  - account.yml
  - daemonset.yml
  - promtail-cm.yml
  - rbac.yml

# secretGenerator:
#   - name: loki
#     files:
#       - secret.yml
