---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: promtail
  app.kubernetes.io/created-by: kustomizer

resources:
- account.yml
- daemonset.yml
- promtail-cm.yml
- rbac.yml
