---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
data:
  config.yml: |-
    server:
      http_listen_port: 3101
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    target_config:
      sync_period: 10s

    scrape_configs:
    - job_name: journal
      journal:
        json: false
        max_age: 12h
        path: /var/log/journal
        matches: _TRANSPORT=kernel
        labels:
          job: systemd-journal
      relabel_configs:
        - source_labels: ['__journal__systemd_unit']
          target_label: 'unit'
    # - job_name: system
    #   system:
    #     json: false
    #     max_age: 24h
    #     path: /var/log/*log
    #   static_configs:
    #   - targets:
    #       - localhost
    #     labels:
    #       job: system-logs
    #       __path__: /var/log/*log

    - job_name: pod-logs
      kubernetes_sd_configs:
        - role: pod
      pipeline_stages:
        - cri: {}
        - docker: {}
      relabel_configs:
        - source_labels:
            - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          replacement: $1
          separator: /
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_name
          target_label: job
        - action: replace
          source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
          target_label: __path__
