---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9080"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: promtail
