---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla
data:
  beyla-config.yml: |
    log_level: WARN
    log_format: json
    shutdown_timeout: 30s
    enforce_sys_caps: true
    trace_printer: disabled
    otel_metrics_export:
      endpoint: http://alloy:4317
      protocol: grpc
      insecure: true
      ttl: 5m
      histogram_aggregation: base2_exponential_bucket_histogram
      instrumentations:
        - "*"
    otel_traces_export:
      endpoint: http://alloy:4317
      protocol: grpc
      insecure: true
      sampler:
        name: parentbased_always_on
    otel_profiles_export:
      endpoint: http://pyroscope:4040
      protocol: grpc
      insecure: true
      retry:
        enabled: true
        initial_interval: 500ms
        max_interval: 5m
        max_elapsed_time: 30s
    discovery:
      instrument:
        - k8s_namespace: .
          containers_only: true
      exclude_instrument:
        - exe_path: ".*tempo.*|.*loki.*|.*prometheus.*|.*mimir.*|.*grafana.*"
    attributes:
      kubernetes:
        enable: true
      select:
        beyla_network_flow_bytes:
          include:
            - beyla.ip
            - src.name
            - dst.port
        sql_client_duration:
          include: ["*"]
          exclude: ["db_statement"]
        http_client_request_duration:
          include: ["*"]
    filter:
      network:
        k8s_dst_owner_name:
          not_match: '{kube*,*alloy*}'
        k8s_src_owner_name:
          not_match: '{kube*,*alloy*}'
    routes:
      unmatched: low-cardinality
      ignored_patterns:
        - /health
        - /healthz
        - /ready
        - /readyz
        - /live
        - /livez
        - /metrics
      ignore_mode: traces
    metrics:
      features:
        - application
        - application_service_graph
        - application_span_otel
    # network: Memory and CPU usage increases as Beyla needs to generate more metrics from network traffic
    network:
      enable: false
      print_flows: false
    ebpf:
      wakeup_len: 128
      high_request_volume: true
      traffic_control_backend: auto
      context_propagation: "all"
    health_check:
      port: 9090
