apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
data:
  tempo.yaml: |
    target: all
    multitenancy_enabled: false
    usage_report:
      reporting_enabled: false
    compactor:
      compaction:
        block_retention: 48h
        compacted_block_retention: 1h
        compaction_cycle: 1h
        compaction_window: 2h
    memberlist:
      bind_addr:
        - '::'
      abort_if_cluster_join_fails: false
    metrics_generator:
      ring:
        kvstore:
          store: memberlist
      processor:
        local_blocks:
          filter_server_spans: true
          flush_to_storage: true
        host_info:
          host_identifiers:
            - k8s.node.name
            - host.id
          metric_name: traces_host_info
        service_graphs:
          wait: 10s
          max_items: 10000
          enable_client_server_prefix: true
          enable_virtual_node_label: true
          enable_messaging_system_latency_histogram: true
        span_metrics:
          enable_target_info: true
      traces_storage:
        path: /var/tempo/generator/traces
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://prometheus-server/api/v1/write
            send_exemplars: true
            name: prometheus
          - url: http://mimir/api/v1/push
            send_exemplars: true
            name: mimir
    distributor:
      max_attribute_bytes: 512
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_http:
              endpoint: 0.0.0.0:14268
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
    server:
      log_level: warn
      log_format: json
      grpc_listen_address: 0.0.0.0
      grpc_listen_port: 9095
      http_listen_address: 0.0.0.0
      http_listen_port: 3100
    storage:
      trace:
        backend: local
        block:
          version: vParquet4
          bloom_filter_false_positive: .05
        local:
          path: /var/tempo/traces
        wal:
          search_encoding: snappy
          path: /var/tempo/wal
    querier:
      max_concurrent_queries: 20
      frontend_worker:
        frontend_address: 0.0.0.0:9095
    query_frontend: {}
    overrides:
      defaults:
        ingestion:
          max_traces_per_user: 0
        metrics_generator:
          processors: [service-graphs, span-metrics, local-blocks]
          generate_native_histograms: both
      user_configurable_overrides:
        api:
          check_for_conflicting_runtime_overrides: true
