---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboards
  labels:
    app.kubernetes.io/name: grafana
data:
  dashboards.yml: |-
    apiVersion: 1
    providers:
      - name: default # A uniquely identifiable name for the provider
        type: file
        allowUiUpdates: false
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  labels:
    app.kubernetes.io/name: grafana
data:
  mimir.yaml: |-
    apiVersion: 1
    datasources:
    - name: Mimir
      type: prometheus
      access: proxy
      editable: true
      isDefault: true
      url: http://mimir/prometheus
      jsonData:
        exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: Tempo
        manageAlerts: true
        prometheusType: Mimir
        maxLines: 1000
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      editable: true
      url: http://prometheus-server
      jsonData:
        exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: Tempo
        manageAlerts: true
        prometheusType: Prometheus
        maxLines: 1000
  pyroscope.yaml: |-
    apiVersion: 1
    datasources:
    - name: Pyroscope
      type: grafana-pyroscope-datasource
      access: proxy
      editable: true
      url: http://pyroscope:4040/
      jsonData:
        minStep: '15s'
  loki.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      editable: true
      url: http://loki:3100
      jsonData:
        maxLines: 1000
        derivedFields:
          - datasourceUid: Tempo
            matcherRegex: '"trace_id":"(.+?)"'
            name: TraceID
            url: "$${__value.raw}"
  tempo.yaml: |-
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      access: proxy
      editable: true
      url: http://tempo:3100
      jsonData:
        httpMethod: GET
        tracesToLogs:
          datasourceUid: Loki
        tracesToLogsV2:
          datasourceUid: Loki
          spanStartTimeShift: '-15m'
          spanEndTimeShift: '15m'
          filterByTraceID: true
        tracesToProfiles:
          datasourceUid: Pyroscope
          tags: ['job', 'instance', 'pod', 'namespace']
          profileTypeId: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds'
          customQuery: true
          query: 'method="$${__span.tags.method}"'
        tracesToMetrics:
          datasourceUid: Mimir
        serviceMap:
          datasourceUid: Mimir
        nodeGraph:
          enabled: true
        search:
          hide: false
        lokiSearch:
          datasourceUid: Loki
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  labels:
    app.kubernetes.io/name: grafana
data:
  grafana.ini: |-
    instance_name=${HOSTNAME}
    [explore]
    enabled=true
    [log]
    mode = console
    level = warn
    [log.console]
    format = json
    [feature_toggles]
    enable=true
    alertRuleRestore=true
    azureMonitorLogsBuilderEditor=true
    elasticsearchCrossClusterSearch=true
    externalServiceAccounts=true
    faroDatasourceSelector=true
    grafanaAdvisor=true
    logsPanelControls=true
    nestedFolders=false
    panelTitleSearch=true
    provisioning=true
    kubernetesDashboards=true
    pdfTables=true
    sqlDatasourceDatabaseSelection=true
    [feature_management]
    allow_editing=true
    [plugins]
    enable_alpha=true
    plugin_admin_enabled=true
    preinstall_async=false
    preinstall=aws-datasource-provisioner-app,grafana-llm-app,grafana-synthetic-monitoring-app,redis-explorer-app,grafana-oncall-app,grafana-investigations-app,grafana-github-datasource,grafana-resourcesexporter-app,grafana-advisor-app,grafana-x-ray-datasource,grafana-guidedtour-panel,grafana-opensearch-datasource,computest-cloudwatchalarm-datasource,grafana-googlesheets-datasource,victoriametrics-logs-datasource,victoriametrics-metrics-datasource,googlecloud-trace-datasource
