---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
