---
# Source: alloy/templates/controllers/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  labels:
    app.kubernetes.io/name: alloy
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: alloy
        prometheus.io/scrape: "true"
        prometheus.io/port: "12345"
        filter.by.port.name: "true"
      labels:
        app.kubernetes.io/name: alloy
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: alloy
      enableServiceLinks: false
      securityContext:
        appArmorProfile:
          type: "Unconfined"
      containers:
        - name: alloy
          image: docker.io/grafana/alloy:v1.10.0
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/tmp/alloy
            - --server.http.listen-addr=$(POD_IP):12345
            - --server.http.ui-path-prefix=/
            - --stability.level=experimental
            - --feature.community-components.enabled
          env:
            - name: ALLOY_DEPLOY_MODE
              value: "helm"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BEYLA_KUBE_METADATA_ENABLE
              value: "autodetect"
            - name: BEYLA_KUBE_CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: GOMEMLIMIT
              value: "1GiB"
          ports:
            - name: metrics
              containerPort: 12345
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              cpu: 100m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 12345
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            runAsUser: 0
            capabilities:
              add:
              - BPF                 # <-- Important. Required for most eBPF probes to function correctly.
              - CAP_CHECKPOINT_RESTORENET_RAW  # <-- Important. Allows Beyla to open ELF files.
              - DAC_READ_SEARCH     # <-- Important. Allows Beyla to open ELF files.
              - NET_ADMIN           # <-- Important. Allows Beyla to inject HTTP and TCP context propagation information.
              - NET_RAW             # <-- Important. Allows Beyla to use socket filters for http requests.
              - PERFMON             # <-- Important. Allows Beyla to load BPF programs.
              - SYS_PTRACE          # <-- Important. Allows Beyla to access the container namespaces and inspect executables.
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: tmp
              mountPath: /tmp/alloy
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: alloy
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
