---
apiVersion: v1
kind: Service
metadata:
  name: alloy
  labels:
    app.kubernetes.io/name: alloy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alloy
  internalTrafficPolicy: Cluster
  ports:
    - name: metrics
      port: 12345
      targetPort: 12345
      protocol: TCP
    - name: grpc-tempo-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: http-tempo-otlp
      port: 4318
      protocol: TCP
      targetPort: 4318
